# Generated by Django 5.1.6 on 2025-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translated',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=40)),
                ('text_boolean', models.BooleanField(default=False)),
                ('image_boolean', models.BooleanField(default=False)),
                ('image_to_translate', models.ImageField(default=None, upload_to='')),
                ('text_to_translate', models.CharField(max_length=400)),
                ('detected_language', models.CharField(max_length=2)),
                ('translated_results', models.CharField(max_length=400)),
            ],
        ),
    ]
