# Generated by Django 5.1.6 on 2025-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField(default='05-07-2025 20:59:58')),
                ('text_boolean', models.BooleanField(default=False)),
                ('image_boolean', models.BooleanField(default=False)),
                ('image_to_translate', models.CharField(max_length=400, null=True)),
                ('text_to_translate', models.CharField(max_length=400)),
                ('detected_language', models.CharField(max_length=30)),
                ('translated_results', models.CharField(max_length=400)),
            ],
        ),
    ]
