# Generated by Django 5.1.6 on 2025-05-08 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 13, 57, 57, 997060)),
        ),
    ]
