# Generated by Django 5.1.6 on 2025-05-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatehistory',
            name='date',
            field=models.DateTimeField(default='05-07-2025 21:00:14'),
        ),
    ]
