# Generated by Django 5.1.6 on 2025-04-21 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 16, 15, 54, 486467)),
        ),
    ]
