# Generated by Django 5.1.6 on 2025-03-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0002_translated_alter_clicklate_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clicklate',
        ),
    ]
