# Generated by Django 5.1.6 on 2025-04-21 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0002_alter_translatehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 16, 16, 18, 378523)),
        ),
    ]
