# Generated by Django 5.1.6 on 2025-04-28 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0003_alter_translatehistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 10, 1, 4, 690728)),
        ),
        migrations.AlterField(
            model_name='translatehistory',
            name='detected_language',
            field=models.CharField(max_length=30),
        ),
    ]
