# Generated by Django 5.1.6 on 2025-03-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0003_delete_clicklate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translated',
            name='date_translated',
        ),
        migrations.RemoveField(
            model_name='translated',
            name='detected_language',
        ),
        migrations.RemoveField(
            model_name='translated',
            name='image_boolean',
        ),
        migrations.RemoveField(
            model_name='translated',
            name='text_boolean',
        ),
        migrations.RemoveField(
            model_name='translated',
            name='translate_to_language',
        ),
    ]
