# Generated by Django 5.1.6 on 2025-04-28 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicklate', '0004_alter_translatehistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 10, 1, 18, 225742)),
        ),
    ]
